// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxao_f5mRpHmnyhmrHZLoyuagd5sM5ZY',
    appId: '1:122462051852:web:5b7d6e7036b17b6c57d829',
    messagingSenderId: '122462051852',
    projectId: 'savvy-1118b',
    authDomain: 'savvy-1118b.firebaseapp.com',
    storageBucket: 'savvy-1118b.appspot.com',
    measurementId: 'G-VDS85LLQG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBRTQTfm5KGFPh68ITIL-peAGqZnoz9E',
    appId: '1:122462051852:android:0707f07c4ff9ccc457d829',
    messagingSenderId: '122462051852',
    projectId: 'savvy-1118b',
    storageBucket: 'savvy-1118b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGmb5edrGzlLZNw9Df4yqxcEEPAvElIo',
    appId: '1:122462051852:ios:42518ab976689f7d57d829',
    messagingSenderId: '122462051852',
    projectId: 'savvy-1118b',
    storageBucket: 'savvy-1118b.appspot.com',
    iosBundleId: 'com.example.savvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABGmb5edrGzlLZNw9Df4yqxcEEPAvElIo',
    appId: '1:122462051852:ios:fc15651d3598480257d829',
    messagingSenderId: '122462051852',
    projectId: 'savvy-1118b',
    storageBucket: 'savvy-1118b.appspot.com',
    iosBundleId: 'com.example.savvy.RunnerTests',
  );
}
